---
title: "Primary analysis"
output: html_notebook
---

+ Compare additions of poverty measures to baseline model 

```{r setup}

set.seed(0000)

library(tidyverse)
library(gtools)
library(ggmap)
library(sf)
library(patchwork)
library(brms)
library(spdep)
library(tidybayes)
library(sjPlot)
library(bayesplot)
library(broom.mixed)
# library(gstat)

# devtools::install_github("m-clark/visibly")
# library(visibly)

theme_set(theme_minimal())

figdir <- "figures/fit"

# Fix default ggsave background
ggsave <- function(..., bg = 'white') ggplot2::ggsave(..., bg = bg)

```

```{r load_data}

# source(here::here("code/load_data.R"), echo=TRUE)
dat_nona <- readRDS(here::here("data","analysis_data_primary.rds"))
fit_base <- readRDS(here::here("output","fit_base.rds"))

dat_nona %>% 
  dplyr::select(test01, sex, agegp, hiv, pov_score, pov01, pov_score_scale, wealth_quant, wealth_step, know_test, know_trt, know_died) %>% 
  summary()

summary(fit_base)
exp(fixef(fit_base))

```

```{r interpret_base}

hyp <- c(oldermen = "sexMale + agegp54120 + sexMale:agegp54120 = 0")

oldermen <- hypothesis(fit_base, hyp)
oldermen
exp(oldermen$hypothesis$Estimate)
exp(oldermen$hypothesis$CI.Lower)
exp(oldermen$hypothesis$CI.Upper)

```

## Spatial autocorrelation in fitted IID

```{r moran_fit_base}

clust <- readRDS(here::here("data","clusters.rds")) %>% # Survey clusters
  mutate(clustid = as.numeric(gsub("c","",cluster))) %>% 
  st_transform(st_crs(4326)) 

fit_base %>%
  spread_draws(r_clustid[clustid,]) %>%
  summarise_draws() -> fitted_iid

dat_sf <- clust %>% 
  full_join(fitted_iid)

# Specify cluster neighbour structure/weights
nb <- poly2nb(dat_sf)
lw <- nb2listw(nb, style = "B", zero.policy = TRUE)

MC <- moran.mc(dat_sf$mean, lw, nsim=999, zero.policy = TRUE, alternative = "greater")
plot(MC)
MC

```

## Fit with poverty measures

```{r priors}

priors <- c(prior(normal(-2, 2), class = Intercept),
            prior(normal(0,10), class = b),
            prior(cauchy(0,1), class = sd, group = "clustid"))

```

```{r add_pov}

# Explore relative significance of the two poverty measures
f2 <- test01 ~ sex*agegp + hiv + wealth_quant + (1 | clustid)
f3 <- test01 ~ sex*agegp + hiv + wealth_step + (1 | clustid)

f.list <- list(score_q = f2, 
               step = f3)

fit_list_pov <- lapply(f.list, 
                       function(f) brm(f, data = dat_nona, prior = priors, family = "bernoulli"))
saveRDS(fit_list_pov, here::here("output","fit_list_pov.rds"))

```

```{r summ_pov}

summ_list_pov <- lapply(fit_list_pov, summary)

bind_rows(
  summary(fit_base)$random$clustid,
  bind_rows(lapply(summ_list_pov, 
                   function(summ) summ$random$clustid))) %>% 
  mutate(Model = factor(c("Baseline","PMT score quantile", "Self-assessed wealth"))) -> ranef_sd_tab

ranef_sd_tab %>% 
  ggplot(aes(Estimate, Model, xmin = `l-95% CI`, xmax = `u-95% CI`)) +
  geom_errorbar(width = 0.2) +
  geom_point() +
  labs(y = "", x = "Estimated SD of random intercept") +
  scale_y_discrete(limits = rev(levels(ranef_sd_tab$Model))) -> pov_clustsd

pov_clustsd
ggsave(here::here(figdir, "compare_reffSD_pov.png"), pov_clustsd, height = 6, width = 6)

```

```{r comp_looic}

fit_base <- add_criterion(fit_base, "loo")
fit_list_pov <- lapply(fit_list_pov, add_criterion, "loo")

loo_comp <- lapply(fit_list_pov, function(fit) loo_compare(fit_base, fit, criterion = "loo"))
loo_comp

mod_wts <- lapply(fit_list_pov, function(fit) model_weights(fit_base, fit))
mod_wts

```

```{r plot_fixeff}

plot_fixeff <- function(fit, order = NULL, labs = NULL, title = NULL){
  plot_model(fit, 
             order.terms = order,
             transform = NULL, 
             title = title,
             axis.labels = labs) + 
    geom_hline(yintercept = 0, lty = "dashed", col = "grey") -> p
  return(p)
}

lapply(fit_list_pov, plot_fixeff)

```

```{r tidy_pov_fixeff}

get_model_data(fit_list_pov[[1]], type = "est", terms = paste0("wealth_quant",2:6)) %>% 
  bind_rows(get_model_data(fit_list_pov[[2]], type = "est", terms = paste0("wealth_step",2:6))) %>% 
  mutate(order = row_number(),
         term = factor(term)) -> ORtab

ORtab

```

```{r plot_pov_fixeff}

labs <- c("PMT score - 2nd quantile",
          "3rd quantile",
          "4th quantile",
          "5th quantile",
          "6th quantile",
          "Self-assessed wealth - 2nd step",
          "3rd step",
          "4th step",
          "5th step",
          "6th step")

get_model_data(fit_list_pov[[1]], type = "est", terms = paste0("wealth_quant",2:6), transform = NULL) %>% 
  bind_rows(get_model_data(fit_list_pov[[2]], type = "est", terms = paste0("wealth_step",2:6), 
                           transform = NULL)) %>%
  mutate(order = row_number(),
         term = factor(term, levels = c(paste0("wealth_quant",2:6),paste0("wealth_step",2:6))),
         level = as.numeric(gsub("wealth_quant", "", gsub("wealth_step","",term)))) %>% 
  ungroup() -> logORtab

logORtab %>% 
  ggplot(aes(term, estimate, col = level)) +
  geom_hline(yintercept = 0, col = "grey", lty = "dashed") +
  geom_vline(xintercept = 5.5, col = "grey") +
  geom_linerange(aes(ymin = conf.low, ymax = conf.high), lwd = 1) +
  geom_linerange(aes(ymin = conf.low50, ymax = conf.high50), lwd = 1.2) +
  geom_point() +
  coord_flip() +
  scale_x_discrete(limits = rev(levels(logORtab$term)), labels = rev(labs)) +
  guides(col = "none") +
  labs(x = "", y = "Estimate (log-odds ratio)") -> pov_coeffs

ggsave(here::here(figdir, "compare_pov_coeffs.png"), pov_coeffs, height = 6, width = 6)

pov_coeffs + pov_clustsd + plot_annotation(tag_levels = 'A')
ggsave(here::here(figdir, "compare_pov_mods.png"), height = 6, width = 12)

```

```{r marg_pov}

fit_list_pov$score_q %>% 
  emmeans::emmeans(~ wealth_quant,
          at = list(sex = "Female",
                    agegp = "(24,34]",
                    hiv = "HIV negative"),
          epred = TRUE) %>% 
  gather_emmeans_draws() -> emmeans_pov

ggplot(emmeans_pov, aes(x = wealth_quant, y = .value, fill = wealth_quant)) +
  stat_halfeye() +
  scale_fill_discrete() +
  labs(x = "Average marginal effect of PMT score quantile", y = "Density") +
  theme(legend.position = "bottom")

emmeans_pov %>% 
  mean_hdi() %>%
  ggplot(aes(wealth_quant, y = .value, ymin = .lower, ymax = .upper)) +
  geom_errorbar(width = 0.3) +
  geom_point() +
  labs(x = "PMT score quantile", y = "Estimated marginal mean")

```
## Continuous space

Consider potential spatial pattern by household GPS location.

```{r by_hh_smooth}

# dat_sp <- dat_nona
# coordinates(dat_sp) <- ~ gps_lat + gps_lng
# 
# # Calculate variogram
# vgm <- variogram(ever_test ~ agegp*sex + hiv, data = dat_sp, cressie = TRUE) 
# plot(vgm, xlab = "Distance")
# 
# vfit <- fit.variogram(vgm, model = vgm(model = "Mat")) 
# plot(vgm, vfit) 
# 
# png(here::here(figdir, "vgm_test01_hh.png"), height = 400, width = 400)
# plot(vgm, vfit) 
# dev.off()
# 
# 
# # Make grid
# proj <- CRS("+init=epsg:4326")
# clust %>% 
#   st_transform(proj) %>% 
#   as_Spatial() -> clust_sp
# 
# grd <- makegrid(clust_sp, n = 5000)
# colnames(grd) <- c("x", "y")
# plot(grd)
# 
# grd_sp <- SpatialPoints(coords = grd, proj4string = proj)
# 
# kriged <- krige(test01 ~ 1, dat_sp, grd_sp, model=vfit)
# 
# ggmap(blt_lines, 
#       base_layer = ggplot(data = as.data.frame(kriged2), 
#                           aes(x=x, y=y, fill = var1.pred))) +
#   geom_tile(alpha = 0.5) +
#   scale_fill_viridis_c(option = "inferno", direction = 1) +
#   labs(x = "", y = "", 
#        lty = "", pch = "", fill = "",
#        subtitle = "Kriged self-reported level, by household location") -> sr_krig
# ggsave(here::here(figdir,"hh_sr_kriged_scaled.png"), sr_krig, height = 5, width = 6)
# 
# 
# 
# coo <- st_coordinates(st_as_sf(dat_sp))
# 
# nn_dist <- spatstat.geom::nndist(unique(coo), k = 1)
# summary(nn_dist)
# #      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
# # 1.036e-05 2.615e-04 4.755e-04 5.979e-04 8.120e-04 6.840e-03 
# 
# S.dist  <-  spdep::dnearneigh(coo, 0, max(nn_dist))  
# lw <- nb2listw(S.dist, style="W") 
# 
# MI  <-  moran.mc(dat_nona$test01, lw, nsim=1000) 
# plot(MI, main="Testing history", las=1) 
# MI
# 
# # Fitted cluster IIDs
# nb <- poly2nb(clust, snap = 0.001)
# 
# # Cluster 31 has no neighbours - impute as 27 for completeness
# nb[[31]] = as.integer(27)
# 
# lw <- nb2listw(nb, style="B", zero.policy=TRUE)
# 
# MI  <-  moran.mc(summary(fit_base)$random$clustid$Estimate, lw, nsim=1000) 
# plot(MI, main="Testing history", las=1) 
# MI
```

```{r fit_cont_hhgps}

# priors2 <- c(prior(normal(-2, 2), class = Intercept),
#             prior(normal(0,10), class = b))
# 
# f0a <- test01 ~ sex*agegp + hiv + gp(gps_lat, gps_lng)
# 
# fit_cont <- brm(f0a, data = dat_nona, prior = priors2, family = "bernoulli")
# saveRDS(fit_cont, here::here("output","fit_base_cont.rds"))

```


## Risk perception

```{r corr_riskperc}

t1 <- table(dat_nona$know_test, dat_nona$know_trt)
chisq.test(t1)
prop.table(t1)

prop.table(table(dat_nona$know_test, dat_nona$know_died))

prop.table(table(dat_nona$know_trt, dat_nona$know_died))
```

```{r add_riskperc}

f4 <- test01 ~ sex*agegp + hiv + know_test + (1 | clustid)
f5 <- test01 ~ sex*agegp + hiv + know_trt + (1 | clustid)
f6 <- test01 ~ sex*agegp + hiv + know_died + (1 | clustid)

f.list2 <- list(know_test = f4,
               know_trt = f5, 
               know_died = f6)

fit_list_rp <- lapply(f.list2, 
                       function(f) brm(f, data = dat_nona, prior = priors, family = "bernoulli"))
saveRDS(fit_list_rp, here::here("output","fit_list_rp.rds"))

```

```{r summ_riskperc}

summ_list_rp <- lapply(fit_list_rp, summary)

bind_rows(
  ranef_sd_tab,
  bind_rows(lapply(summ_list_rp, 
                   function(summ) summ$random$clustid))) %>% 
  mutate(Model = factor(c("Baseline", "PMT score quantile", "Self-assessed wealth",
                          "Know tested","Know treated","Know died"))) -> ranef_sd_tab

ranef_sd_tab %>% 
  ggplot(aes(Estimate, Model, xmin = `l-95% CI`, xmax = `u-95% CI`)) +
  geom_errorbar(width = 0.2) +
  geom_point() +
  labs(y = "", x = "Estimated SD of random intercept") +
  scale_y_discrete(limits = rev(levels(ranef_sd_tab$Model)))

ggsave(here::here(figdir, "compare_reffSD_pov_rp.png"), height = 6, width = 6)

```

